version: '3.9'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www   # ← ここを ./src:/var/www から修正
    working_dir: /var/www
    container_name: third-php

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www   # ← ここも修正
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: third-nginx

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: Asia/Tokyo
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    container_name: third-mysql

volumes:
  db_data:
